### ISSUE TITLE
Is There A Way To Get Stream Mode on DesktopCamera

### ISSUE THREAD

**Issue by VelvetDash5** [d-mageek/VRC-Mods#9]
My Friend On Discord Wants Stream Mode but idk stream mode has disappeared or replaced camera
Did you Know How That Happen
Did it just Replace PC Camera as Quest Camera
or Forgotten Stream Mode With UI Mask I Think Users can See Quick Menu and they know how to turn it off within UI Mask
Thank You For Understanding
From:
aortiz294_bf99

**Comment by oestradiol** [comment]
Hey, sorry for the late response!
That change was made by Nirvash, in a PR, which I later on merged in.
And since they updated it, I gave them permissions to update this mod by themselves, and so you might also ask them if you want :3
[Nirvash#0001](https://github.com/Nirv-git)

**Comment by VelvetDash5** [comment]
Ok thank you
